version: "3"
services:
  minecraft:
    image: openjdk:latest
    working_dir: /usr/app
    volumes:
      - ./server:/usr/app
    ports:
      - "25565:25565"
    command: java -Xmx1024M -Xms1024M -jar server.jar nogui
networks:
  default:
    driver: bridge
