version: "3"
services:
  crawler:
    image: openjdk:latest
    working_dir: /usr/app
    volumes:
      - ./server:/usr/app
    tty: true
    ports:
      - 25565:25565
    command: java -Xmx1024M -Xms1024M -jar server.jar nogui
